services:
  django:
    build: ./app
    container_name: django-web-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`weasyprint-django-backend-xymmxy-eb9ae5-83-228-210-135.traefik.me`)"
      - "traefik.http.routers.django.entrypoints=web"
      # - "traefik.http.routers.django.tls.certresolver=myresolver"
      - "traefik.http.services.django.loadbalancer.server.port=8000"


  database:
    container_name: postgresql-database
    image: postgres:17
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: